AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for serverless app with SAM CLI using Java runtime

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  GreetingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/GreetingFunction-1.0.jar
      Handler: com.smuralee.App::handleRequest
      Runtime: java8
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Greeting:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /greeting
            Method: get
  LoyaltyPointsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/LoyaltyPointsFunction-1.0.jar
      Handler: com.smuralee.App::handleRequest
      Runtime: java8
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        LoyaltyPoints:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /loyalty-points
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GreetingApi:
    Description: "API Gateway endpoint URL for Prod stage for Greeting function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greeting/"
  GreetingFunction:
    Description: "Greeting Lambda Function ARN"
    Value: !GetAtt GreetingFunction.Arn
  GreetingFunctionIamRole:
    Description: "Implicit IAM Role created for Greeting function"
    Value: !GetAtt GreetingFunctionRole.Arn
  LoyaltyPointsApi:
    Description: "API Gateway endpoint URL for Prod stage for LoyaltyPoints function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/loyalty-points/"
  LoyaltyPointsFunction:
     Description: "LoyaltyPoints Lambda Function ARN"
     Value: !GetAtt LoyaltyPointsFunction.Arn
  LoyaltyPointsFunctionIamRole:
     Description: "Implicit IAM Role created for LoyaltyPoints function"
     Value: !GetAtt LoyaltyPointsFunctionRole.Arn
